default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: balaji
  password: database123
  host: localhost

development:
  <<: *default
  database: lms_development

test:
  <<: *default
  database: lms_test

production:
  <<: *default
  database: lms_production
